#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: Hacker theme

# Short bio or description (displayed in the header)
description: Hacker is a theme for GitHub Pages.

author:
  name: John Doe

logo:

giscus:
  # repo:
  # repo_id:
  # category: Comments
  # category_id:
  # mapping: pathname
  # strict: 0
  # reactions_enabled: 1
  # emit_metadata: 0
  # theme: dark
  # lang: en
  # loading: lazy
  # crossorigin: anonymous

# JSON-LD
bio:
  gender: male
  employer_name: Unknown
  employer_url: https://unknown.com
  job_title: mock

# Includes an icon in the footer for each username you enter
social-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  keybase:
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>

social:
  name: John Doe
  links: 
    - https://github.com/John-Doe

# Contact form script id that points to google macros (e.g. https://script.google.com/macros/s/<script-identifier>/exec)
contact_form_script_id: <script-identifier>

# Visitor notifier based on IFTTT + Webhooks. Sample here - /assets/js/monitor.js
monitor: false

pgp-key:
  show: false
  url:
  fingerprint:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

paginate: 5

permalink: pretty

excerpt_separator: <!--more-->

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""
lang: en-US

show_downloads: false

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      comments: false

# Set the Sass partials directory, as we're using @imports
# sass:
#   style: :expanded # You might prefer to minify using :compressed
sass:
  style: compressed

# Use the following plug-ins
plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-gist
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - docs
  - thumbnail.png
  - jekyll-theme-hacker.gemspec
