on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
