on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
